version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: yemiwebby/building-on-ci
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build --no-cache -t $IMAGE_NAME:latest .
workflows:
  version: 2
  build-main:
    jobs:
      - build:
          filters:
            branches:
              only: main
